# Part 1 (Acho que vou quebrar em lições como o autor)

## Vetores, Arrays e Matrizes

Fonte: https://lectures.quantecon.org/jl/julia_arrays.html

Podemos verificar a dimensão ou tamanho de arrays em Julia utilizando a função `size()` ou `ndims()`. Aqui também temos diagonais como no R:

In [1]:
eye(3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [2]:
diagm([1,2,3,4])

4×4 Array{Int64,2}:
 1  0  0  0
 0  2  0  0
 0  0  3  0
 0  0  0  4

Temos zeros (e ones) também.

In [16]:
zeros(3,3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

Os formatos `Array` e `Matrix` são aliases para o tipo Array de uma ou mais dimensões. Adicionalmente, é possível mudar as dimensões e um Array utilizando a função `reshape()`. 

In [8]:
a = [1,2,3,4]
b = reshape(a,2,2)
b[1,1] = 10
a #Repare que o reshape ainda aponta para a. Então mudar valores de b muda valores de a

4-element Array{Int64,1}:
 10
  2
  3
  4

In [14]:
a = [1 2 3 4] # linha
#É possivel achatar um array com squeeze()
squeeze(a,1) #Coluna

4-element Array{Int64,1}:
 1
 2
 3
 4

Os Arrays podem ser declarados vazios também, com apenas seus tipos (para depois sofererem trocentos conflitos usando funções...)

In [17]:
Array{Float64}(2,2)

2×2 Array{Float64,2}:
 1.08896e-314  1.06104e-314
 1.06104e-314  1.06158e-314

Eles podem ter quantas dimensões forem necessárias

In [19]:
Array{Float64}(2,2,3,2)

2×2×3×2 Array{Float64,4}:
[:, :, 1, 1] =
 1.47764e248  3.94812e180
 1.16096e-28  1.28626e248

[:, :, 2, 1] =
 4.24949e-86  7.68302e-43
 1.35617e248  7.01941e-33

[:, :, 3, 1] =
 2.1753e-76  5.81073e294
 9.3668e-62  0.0        

[:, :, 1, 2] =
 0.0  0.0
 0.0  0.0

[:, :, 2, 2] =
 0.0  0.0
 0.0  0.0

[:, :, 3, 2] =
 0.0  0.0
 0.0  0.0

Zeros e ones são wrappers para a função `fill()`. 

In [20]:
fill("etc",2,2)

2×2 Array{String,2}:
 "etc"  "etc"
 "etc"  "etc"

Assim como matlab, podemos declarar matrizes usando ; e linhas. Uma diferença do R é que não deixamos vazio na linha/coluna e sim :

In [24]:
A = eye(3)
A[1,:]

3-element Array{Float64,1}:
 1.0
 0.0
 0.0

De forma similar ao R, podemos também extrair elementos usando `true` e `false`

In [29]:
a = [1,2,3,4]
b = [true,false,true,false]
a[b]# 1,3

2-element Array{Int64,1}:
 1
 3

Assim como python, os valores são passados por referencia, não por valor. Basicamente duas variáveis com mesmo nome apontam para o mesmo valor na memória.


In [34]:
a = [1 2 3]
b = a
a[1] = 4
b #o primeiro valor mudou mesmo depois da atribuição "só" em ab
#Caso precisemos de uma cópia, usamos "copy"
a = [1 2 3]
b = copy(a)
a[1] = 4
b #o primeiro valor mudou mesmo depois da atribuição "só" em a


1×3 Array{Int64,2}:
 1  2  3

Métodos usuais se aplicam em arrays: `mean`, `std`, `sum`,`maximum/minimum`, `sort`, etc. Aqui, `*` representa **multiplicação matricial**.

In [38]:
diagm([2,1])*[1;0]

2-element Array{Int64,1}:
 2
 0

Prime é usado pra transpostas

In [39]:
[1 0]'

2×1 Array{Int64,2}:
 1
 0

O sinal de divisão é exótico aqui. Ele parece significar `A\B = inv(A)*B`.

In [44]:
A = [1 2;2 3]
b = ones(2,2)
isequal(A\b, inv(A)*b)

true

Produto interno é embrulhado aqui também, através da função `dot()`.

In [45]:
dot(ones(3),ones(3))

3.0

Operações podem ser realizadas *elementwise* como no R colocando um ponto antes de qualquer operador, como `.+`, etc. (Apesar de que + é um péssimo exemplo xD)

In [47]:
2.*eye(2).*ones(2,2)

2×2 Array{Float64,2}:
 2.0  0.0
 0.0  2.0

Um exemplo melhor é a comparação elementwise. 

In [54]:
zeros(2,2) .< ones(2,2)

2×2 BitArray{2}:
 true  true
 true  true

Que funciona com escalares também 

In [56]:
[1 2 3] .== 1

1×3 BitArray{2}:
 true  false  false

Somando os dois, temos algo parecido com o which do R e os operadores lógicos em data.frames.

In [58]:
a = [2 3 4 2 2 2 3 4 2]
a[a.==2]

5-element Array{Int64,1}:
 2
 2
 2
 2
 2

Para aplicar funções elementwise, me parece mais lógico utilizar uma comprehension. Apesar de log ser vetorizada, faria mais sentido fazer

In [61]:
a = reshape(rand(10),2,5)
[log(elemento) for elemento in a]

2×5 Array{Float64,2}:
 -1.59384  -0.186669  -1.88246   -0.487368  -1.46901
 -1.03622  -0.342207  -0.794505  -4.23129   -4.11664

Além disso, existem outras funções nativas de Algebra Linear, como `det`, `trace`, `rank` e `eigvals`. (http://julia.readthedocs.io/en/latest/stdlib/linalg/)

## Exercícios